name: Fetch Gaming News

on:
  schedule:
    - cron: '0 */2 * * *' # toutes les 2 heures
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests beautifulsoup4
      - name: Run scraper
        run: python fetch_news.py
